name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List files for debugging
      - name: List files for debugging
        run: |
          echo "Root directory:"
          ls -a
          echo "S3 directory contents:"
          ls -a s3
          echo "Contents of s3/index2.html:"
          ls -l s3/index2.html  # Check if the file is present

      # Step 3: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 cp s3/index2.html s3://saadalis3/index2.html --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # Step 4: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          DISTRIBUTION_ID=E3OK8N7LCP7UPL  # Replace with your CloudFront distribution ID
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
